import { UiLanguage } from '../types';

const appCopy = {
  'ar-EG': {
    common: {
      settings: 'الإعدادات',
      reminders: 'تذكيراتك',
      save: 'تم',
      edit: 'تعديل',
      share: 'شارك',
      back: 'رجوع',
      openSystemSettings: 'افتح إعدادات الموبايل',
      tryAgain: 'جرّب تاني',
      openHelp: 'افتح المساعدة',
      allReminders: 'كل التذكيرات',
      today: 'النهارده',
      upcoming: 'الجاي',
      overdue: 'متأخر',
      done: 'تم',
      change: 'غيّر',
      chooseDate: 'اختار اليوم',
      chooseTime: 'اختار الوقت',
    },
    onboarding: {
      eyebrow: 'صوت أولًا',
      title: 'قول اللي وراك، والباقي علينا',
      description: 'اتكلم مرة واحدة. نأكدها بسرعة ونفكرك في وقتها.',
      featureOneTitle: 'اتكلم',
      featureOneText: 'قول المهمة والمعاد بطريقتك',
      featureTwoTitle: 'نأكد ونفكرك',
      featureTwoText: 'مراجعة خفيفة وبعدها التذكير يتظبط لوحده',
      flowSpeak: 'اتكلم',
      flowConfirm: 'نأكد',
      flowRemember: 'نذكرك',
      exampleLabel: 'مثال',
      exampleText: 'فكّرني أكلم أحمد بكرة الساعة ٥',
      cta: 'يلا نبدأ',
    },
    home: {
      brandSubtitle: 'صوت أولًا',
      pendingOne: 'فيه تذكير محفوظ مستني تفعيل الإشعارات.',
      pendingMany: (count: number) => `فيه ${count} تذكيرات محفوظة مستنية تفعيل الإشعارات.`,
      voiceTitleIdle: 'دوس واتكلم',
      voiceTitleProcessing: 'ثانية ونرتبها',
      voiceSubtitleListening: 'قول المهمة والميعاد بس.',
      voiceSubtitlePending: 'راجعها بسرعة أو سيبها تتحفظ لو كلها تمام.',
      voiceSubtitleIdle: 'قول اللي في بالك وإحنا هنظبطه بسرعة.',
      hintIdle: 'اضغط واتكلم',
      hintListening: 'كمّل',
      hintProcessing: 'بنحفظها',
      subhintIdle: 'ضغطة واحدة واتكلم، والباقي علينا.',
      subhintListening: 'قولها بطريقتك وإحنا نكمل الباقي.',
      subhintProcessing: 'مش محتاج تعمل أي حاجة تاني.',
      transcriptPlaceholder: 'مثال: فكّرني بمعاد الدكتور بكرة الساعة ٦',
      exampleLabel: 'جرّب تقول',
      exampleOne: 'فكّرني أكلم أحمد بكرة ٥',
      exampleTwo: 'ذكرني أدفع الإيجار آخر الشهر',
      retryVoice: 'قولها تاني',
      nearestNow: 'الأقرب دلوقتي',
      latestEmptyTitle: 'لسه مفيش حاجة محفوظة',
      latestEmptyText: 'الإضافة اليدوية موجودة جوه شاشة التذكيرات كحل بديل.',
      latestPinnedText: 'مش هتفوتك طول ما الإشعارات شغالة.',
      confirmReady: 'جاهز للحفظ',
      confirmReview: 'محتاج مراجعة',
      confirmTitle: 'ده اللي فهمته',
      confirmWarning:
        'لو في حاجة مش مظبوطة، غيّر اليوم أو الوقت من هنا أو افتح التعديل الكامل.',
      dateLabel: 'اليوم',
      timeLabel: 'الوقت',
      pickDate: 'اختيار اليوم',
      pickTime: 'اختيار الوقت',
      setDate: 'حدد اليوم',
      setTime: 'حدد الوقت',
      pickerDateTitle: 'اختار اليوم',
      pickerTimeTitle: 'اختار الوقت',
      unclearTime: 'الوقت مش واضح',
      unclearDate: 'اليوم مش واضح',
      unclearTitle: 'اسم المهمة محتاج مراجعة',
      lowHint: 'راجعها مرة واحدة وبعدين اضغط تم.',
      highHintPaused: 'الحفظ التلقائي وقف لحد ما تراجع.',
      highHintRunning: 'لو كله تمام، هيتحفظ لوحده خلال ٣ ثواني.',
      savedToast: 'اتحفظ. مش هيضيع.',
      undo: 'تراجع',
      speechPermissionNeeded: 'لازم تسمح بالمايك الأول.',
      enableArabicIos: 'فعّل العربي في إعدادات الجهاز الأول.',
      arabicUnavailable: 'العربي مش متاح على الجهاز ده.',
      parseFailure: 'فيه لخبطة بسيطة. قولها تاني.',
      saveFailure: 'فيه مشكلة في الحفظ. جرّب تاني.',
      voiceEmpty: 'لسه ما قلتش حاجة.',
    },
    reminderList: {
      title: 'اللي عليك دلوقتي',
      subtitle: 'ركّز على النهارده وسيب الباقي برّه الطريق.',
      manualCta: 'إضافة يدوية',
      heroBadge: 'النهارده',
      heroCaption: 'نظرة سريعة على المهم دلوقتي',
      needsActionToday: 'محتاج حركة',
      compactDue: 'محتاجين حركة النهارده',
      compactDone: 'مكتمل',
      emptyTitle: 'لسه مفيش تذكيرات',
      emptySubtitle: 'ابدأ يدوي أو ارجع سجّل بصوتك.',
      addFirstManual: 'أضف أول تذكير يدوي',
      backToVoice: 'ارجع سجّل بالصوت',
      filterQuietTitle: 'الفلاتر هادية دلوقتي',
      filterQuietToday: 'مفيش حاجة محتاجة تدخل النهارده.',
      filterQuietUpcoming: 'مفيش حاجة جاية قريب.',
      filterQuietOverdue: 'عظيم، مفيش حاجة متأخرة دلوقتي.',
      switchFilter: 'بدّل الفلتر',
      doneTitle: 'اللي خلص',
      doneSubtitle: 'هنا بتظهر الحاجات اللي خلصت فعلًا.',
      doneSummary: (count: number) =>
        `خلصت ${count} ${count === 1 ? 'تذكير' : 'تذكيرات'}.`,
      showDone: 'شوف اللي خلص',
      hideDone: 'اخفي المكتمل',
    },
    confirmation: {
      titleEdit: 'عدّل التذكير',
      titleManual: 'أضف تذكير يدوي',
      titleVoice: 'ظبطها بسرعة',
      subtitleEdit: 'عدّل اللي محتاجه واحفظ التغيير.',
      subtitleManual: 'اكتب المهمة وحدد المعاد واحفظها من غير لف كتير.',
      subtitleVoice: 'راجع الضروري بس وبعدها احفظ.',
      heroEdit: 'تعديل',
      heroManual: 'إضافة يدوي',
      heroVoice: 'مراجعة أخيرة',
      heroEditCaption: 'عدّل الوقت أو الاسم لو محتاج.',
      heroManualCaption: 'حدد المهمة والمعاد من غير خطوات زيادة.',
      heroVoiceCaptionNoMissing: 'شكلها مظبوطة. راجعها واحفظ.',
      originalText: 'النص الأصلي',
      heardText: 'النص اللي اتسمع',
      taskName: 'اسم المهمة',
      taskCategory: 'نوع المهمة',
      taskCategorySubtitle: 'اختياري للتنظيم بس.',
      schedule: 'المعاد',
      time: 'الوقت',
      day: 'اليوم',
      reminderTime: 'وقت التنبيه',
      reminderWillArriveAt: (day: string, time: string) => `التنبيه هيوصل: ${day} - ${time}`,
      recurrence: 'التكرار',
      calendar: 'التقويم',
      addToCalendar: 'ضفها للتقويم',
      calendarHint: 'بيتحفظ بنفس منطق التنبيه اللي اخترته هنا.',
      iosCalendarHint: 'التذكير ده هيتحفظ كمان في Apple Calendar تلقائي.',
      saveReminder: 'احفظ التذكير',
      saveEdit: 'احفظ التعديل',
      saving: 'جارٍ الحفظ...',
      clearName: 'لازم اسم المهمة يبقى واضح.',
      futureTime: 'وقت التذكير لازم يكون لسه قدام.',
      needsReview: 'فيه حاجة محتاجة مراجعة.',
      savedTitle: 'التذكير اتحفظ',
      confidenceHigh: 'واضح',
      confidenceMedium: 'متوسط',
      confidenceLow: 'محتاج مراجعة',
    },
    settings: {
      title: 'إعدادات Fakarni',
      subtitle: 'الأساسيات اللي تضمن إن التذكير ما يضيعش.',
      appStatus: 'حالة التطبيق',
      ready: 'جاهز',
      needsStep: 'محتاج خطوة',
      egyptianVoice: 'صوت مصري',
      notificationsOn: 'الإشعارات شغالة',
      notificationsOff: 'الإشعارات لسه مش كاملة',
      essentialsTitle: 'الأساسيات',
      essentialsSubtitle: 'اللغة، الصوت، والإشعارات.',
      promiseTitle: 'قولها وإحنا نكملها',
      promiseText: 'الهدف هنا إن التذكير يتسجل ويتابع معاك من غير قلق.',
      languageTitle: 'اللغة والشكل العام',
      languageSubtitle: 'اختار لغة الواجهة.',
      languageRowTitle: 'لغة التطبيق',
      languageRowSubtitle: 'تقدر تبدل بين المصري والإنجليزي في أي وقت.',
      egyptianArabic: 'مصري',
      english: 'English',
      soundAlertsTitle: 'الصوت والتنبيهات',
      ttsTitle: 'شغّل التذكير بصوت',
      ttsSubtitle: 'بيشتغل وإنت فاتح التطبيق أو لما تدخل من الإشعار.',
      notificationReady: 'الإشعارات شغالة',
      notificationNeedEnable: 'الإشعارات محتاجة تفعيل',
      notificationWaitingMany: (count: number) =>
        `فيه ${count} تذكيرات محفوظة مستنية الإذن عشان نربطها بالإشعارات.`,
      notificationNeedText: 'فعّل الإشعارات عشان التذكيرات توصلك في وقتها.',
      smartFollowTitle: 'متابعة ذكية',
      smartFollowSubtitle: 'نغزة واحدة زيادة لو ما خلصتش التذكير أو أجلته.',
      oneNudge: 'نغزة متابعة واحدة',
      oneNudgeSubtitle: 'من غير تكرار لا نهائي. مجرد نغزة واحدة وقت الحاجة.',
      followDelayTitle: 'تأخير نغزة المتابعة',
      followDelayText: (minutes: number) => `حاليًا بعد ${minutes} دقيقة من التذكير الأساسي.`,
      appleCalendarSubtitle:
        'اختياري. فعلها مرة واحدة وهتتحفظ التذكيرات الجديدة تلقائي.',
      appleCalendarTitle: 'ضف التذكيرات لـ Apple Calendar',
      appleCalendarHint: 'بيتحفظ في الخلفية من غير ما يفتح شاشة حدث جديدة.',
      googleCalendarSubtitle:
        'اختياري. على Android هيتستخدم Google Calendar لو الحساب متوصل.',
      analyticsTitle: 'الخصوصية والثقة',
      analyticsSubtitle:
        'شرح بسيط للبيانات اللي بتتبعت والدعم وإصدار التطبيق.',
      analyticsToggleTitle: 'تحليلات استخدام مجهولة',
      analyticsToggleSubtitle:
        'من غير إرسال الكلام نفسه أو اسم التذكير.',
      trustTitle: 'الثقة والخصوصية',
      trustSubtitle: 'معلومات واضحة عن التحليلات والمساعدة والإصدار.',
      supportTitle: 'المساعدة والدعم',
      supportSubtitle: 'الأسئلة الشائعة والخصوصية وطرق الدعم.',
      versionLabel: 'إصدار التطبيق',
      internalToolsTitle: 'أدوات داخلية',
      internalToolsSubtitle: 'قسم منخفض الأولوية للأحداث وPostHog وحالة الجهاز الحالي.',
      openFounderDashboard: 'افتح Founder Dashboard',
      ghostPersonalityTitle: 'شخصية الجوست',
      ghostPersonalitySubtitle: 'اختار الرد اللي يريحك أكتر',
      helpPrivacyTitle: 'المساعدة والخصوصية',
      helpPrivacyLink: 'الأسئلة الشائعة والخصوصية والدعم',
      adsTitle: 'التحكم في الإعلانات',
      adsSubtitle: 'إعداد داخلي. من هنا تقدر تجهز منطق الإعلانات قبل ما توصلها بـ SDK.',
      adsEnabled: 'تشغيل الإعلانات',
      adsEnabledSubtitle: 'قفلها وفتحها من هنا بدل ما تبقى ثابتة في الكود.',
      adsProvider: 'مزود الإعلانات',
      homeBanner: 'بانر في الهوم',
      homeBannerSubtitle: 'تجهيز فقط. مش ظاهر للمستخدم إلا لما توصل SDK فعلي.',
      interstitialEvery: 'إظهار interstitial بعد كام حركة',
      noInterstitial: 'بدون',
      hideForSubscribers: 'إخفاء الإعلانات عن المشتركين لاحقًا',
      hideForSubscribersSubtitle: 'جاهزة من دلوقتي لسيناريو الاشتراك من غير شغل إضافي.',
      connectGoogle: 'اربط Google Calendar',
      disconnectGoogle: 'افصل Google Calendar',
      connecting: 'جارٍ الربط...',
      disconnecting: 'جارٍ الفصل...',
      notificationActionBlocked: 'افتح إعدادات الموبايل',
      notificationActionAsk: 'فعّل الإشعارات',
    },
    help: {
      title: 'المساعدة والخصوصية',
      privacyTitle: 'ملخص الخصوصية',
      privacySubtitle: 'ملخص سريع يشرح للمستخدم إيه اللي بيحصل جوه التطبيق.',
      permissionsTitle: 'الإشعارات والصلاحيات',
      deviceDataTitle: 'البيانات على موبايلك',
      resetAllData: 'امسح كل البيانات المحلية',
      resetTitle: 'مسح البيانات المحلية',
      resetBody: 'هيمسح كل التذكيرات والإعدادات المخزنة على الموبايل ده بس.',
      cancel: 'إلغاء',
      reset: 'مسح',
    },
    speechFailed: {
      title: 'التسجيل ما كملش زي ما كنا عايزين',
      transcriptLabel: 'النص اللي اتلقط',
    },
  },
  en: {
    common: {
      settings: 'Settings',
      reminders: 'Reminders',
      save: 'Done',
      edit: 'Edit',
      share: 'Share',
      back: 'Back',
      openSystemSettings: 'Open device settings',
      tryAgain: 'Try again',
      openHelp: 'Open help',
      allReminders: 'All reminders',
      today: 'Today',
      upcoming: 'Upcoming',
      overdue: 'Overdue',
      done: 'Done',
      change: 'Change',
      chooseDate: 'Choose day',
      chooseTime: 'Choose time',
    },
    onboarding: {
      eyebrow: 'Voice first',
      title: 'Say it once. We handle the rest.',
      description: 'Speak, review quickly, and trust the reminder will not slip.',
      featureOneTitle: 'Speak',
      featureOneText: 'Say the task and time naturally',
      featureTwoTitle: 'Confirm and remember',
      featureTwoText: 'Quick review, then the reminder keeps up with you',
      flowSpeak: 'Speak',
      flowConfirm: 'Confirm',
      flowRemember: 'Reminder',
      exampleLabel: 'Example',
      exampleText: 'Remind me to call Ahmed tomorrow at 5',
      cta: 'Get started',
    },
    home: {
      brandSubtitle: 'Voice first',
      pendingOne: '1 saved reminder is waiting for notifications to be enabled.',
      pendingMany: (count: number) =>
        `${count} saved reminders are waiting for notifications to be enabled.`,
      voiceTitleIdle: 'Tap and speak',
      voiceTitleProcessing: 'One second',
      voiceSubtitleListening: 'Just say the task and time.',
      voiceSubtitlePending: 'Review it quickly or let it auto-save if it looks right.',
      voiceSubtitleIdle: 'Say what you need and it becomes a reminder fast.',
      hintIdle: 'Tap and speak',
      hintListening: 'Keep going',
      hintProcessing: 'Saving',
      subhintIdle: 'One tap, then speak. We handle the rest.',
      subhintListening: 'Say it naturally and we will take care of the rest.',
      subhintProcessing: 'You do not need any extra steps.',
      transcriptPlaceholder: 'Example: Remind me about the doctor tomorrow at 6',
      exampleLabel: 'Try saying',
      exampleOne: 'Remind me to call Ahmed tomorrow at 5',
      exampleTwo: 'Remind me to pay rent at the end of the month',
      retryVoice: 'Say it again',
      nearestNow: 'Up next',
      latestEmptyTitle: 'Nothing saved yet',
      latestEmptyText: 'Manual entry still exists inside the reminders screen as a fallback.',
      latestPinnedText: 'It will not slip if notifications stay enabled.',
      confirmReady: 'Ready to save',
      confirmReview: 'Needs review',
      confirmTitle: 'This is what I understood',
      confirmWarning:
        'If anything looks off, change the day or time here, or open full edit.',
      dateLabel: 'Day',
      timeLabel: 'Time',
      pickDate: 'Pick day',
      pickTime: 'Pick time',
      setDate: 'Choose day',
      setTime: 'Choose time',
      pickerDateTitle: 'Choose day',
      pickerTimeTitle: 'Choose time',
      unclearTime: 'Time is unclear',
      unclearDate: 'Day is unclear',
      unclearTitle: 'Task name needs review',
      lowHint: 'Review it once, then tap Done.',
      highHintPaused: 'Auto-save is paused until you review it.',
      highHintRunning: 'If it looks right, it will save itself in 3 seconds.',
      savedToast: 'Saved. It will not slip.',
      undo: 'Undo',
      speechPermissionNeeded: 'Microphone permission is required first.',
      enableArabicIos: 'Enable Arabic on the device first.',
      arabicUnavailable: 'Arabic speech is not available on this device.',
      parseFailure: 'Something was unclear. Say it again.',
      saveFailure: 'Saving failed. Please try again.',
      voiceEmpty: 'No speech was captured yet.',
    },
    reminderList: {
      title: 'What needs action now',
      subtitle: 'Focus on today and keep the rest out of the way.',
      manualCta: 'Manual entry',
      heroBadge: 'Today',
      heroCaption: 'A quick view of what matters now',
      needsActionToday: 'Need action',
      compactDue: 'Need action today',
      compactDone: 'Completed',
      emptyTitle: 'No reminders yet',
      emptySubtitle: 'Start manually or go back to voice.',
      addFirstManual: 'Add your first manual reminder',
      backToVoice: 'Back to voice',
      filterQuietTitle: 'Nothing in this filter right now',
      filterQuietToday: 'Nothing needs action today.',
      filterQuietUpcoming: 'Nothing is coming up soon.',
      filterQuietOverdue: 'Nice. Nothing is overdue right now.',
      switchFilter: 'Switch filter',
      doneTitle: 'Completed',
      doneSubtitle: 'One-time reminders that are fully done show up here.',
      doneSummary: (count: number) => `You completed ${count} reminder${count === 1 ? '' : 's'}.`,
      showDone: 'Show completed',
      hideDone: 'Hide completed',
    },
    confirmation: {
      titleEdit: 'Edit reminder',
      titleManual: 'Add reminder manually',
      titleVoice: 'Quick review',
      subtitleEdit: 'Change what you need and save the update.',
      subtitleManual: 'Enter the task and time, then save without extra steps.',
      subtitleVoice: 'Review only what matters, then save.',
      heroEdit: 'Edit',
      heroManual: 'Manual',
      heroVoice: 'Final review',
      heroEditCaption: 'Update the title or timing if needed.',
      heroManualCaption: 'Set the task and timing without extra steps.',
      heroVoiceCaptionNoMissing: 'It looks right. Review and save.',
      originalText: 'Original text',
      heardText: 'Captured text',
      taskName: 'Task name',
      taskCategory: 'Category',
      taskCategorySubtitle: 'Optional organization only.',
      schedule: 'Schedule',
      time: 'Time',
      day: 'Day',
      reminderTime: 'Reminder time',
      reminderWillArriveAt: (day: string, time: string) => `Notification will arrive: ${day} - ${time}`,
      recurrence: 'Recurrence',
      calendar: 'Calendar',
      addToCalendar: 'Add to calendar',
      calendarHint: 'Uses the same reminder timing you selected here.',
      iosCalendarHint: 'This reminder will also save to Apple Calendar automatically.',
      saveReminder: 'Save reminder',
      saveEdit: 'Save changes',
      saving: 'Saving...',
      clearName: 'The task name needs to be clear.',
      futureTime: 'The reminder time must still be in the future.',
      needsReview: 'Something still needs review.',
      savedTitle: 'Reminder saved',
      confidenceHigh: 'Clear',
      confidenceMedium: 'Medium',
      confidenceLow: 'Needs review',
    },
    settings: {
      title: 'Fakarni Settings',
      subtitle: 'The basics that keep reminders reliable.',
      appStatus: 'App status',
      ready: 'Ready',
      needsStep: 'Needs one step',
      egyptianVoice: 'Egyptian voice',
      notificationsOn: 'Notifications on',
      notificationsOff: 'Notifications incomplete',
      essentialsTitle: 'Core setup',
      essentialsSubtitle: 'Language, voice, and notifications.',
      promiseTitle: 'Say it and it gets handled',
      promiseText: 'The priority here is reliability, not extra complexity.',
      languageTitle: 'Language and tone',
      languageSubtitle: 'Choose your interface language.',
      languageRowTitle: 'App language',
      languageRowSubtitle: 'You can switch between Egyptian Arabic and English any time.',
      egyptianArabic: 'Egyptian Arabic',
      english: 'English',
      soundAlertsTitle: 'Voice and alerts',
      ttsTitle: 'Play reminders with voice',
      ttsSubtitle: 'Works while the app is open or when returning from a notification.',
      notificationReady: 'Notifications are working',
      notificationNeedEnable: 'Notifications need to be enabled',
      notificationWaitingMany: (count: number) =>
        `${count} saved reminders are waiting for permission before their notifications can be scheduled.`,
      notificationNeedText: 'Enable notifications so reminders arrive on time.',
      smartFollowTitle: 'Smart follow-up',
      smartFollowSubtitle: 'Send one extra nudge only if the reminder was ignored.',
      oneNudge: 'One follow-up nudge',
      oneNudgeSubtitle: 'No endless retries. Just one extra reminder when needed.',
      followDelayTitle: 'Follow-up delay',
      followDelayText: (minutes: number) => `Currently ${minutes} minutes after the main reminder.`,
      appleCalendarSubtitle: 'Optional. Enable once and future reminders will save automatically.',
      appleCalendarTitle: 'Add reminders to Apple Calendar',
      appleCalendarHint: 'Saves silently in the background without opening event creation UI.',
      googleCalendarSubtitle: 'Optional. On Android, Google Calendar will be used when connected.',
      analyticsTitle: 'Privacy and trust',
      analyticsSubtitle: 'Clear info about analytics, support, and app version.',
      analyticsToggleTitle: 'Anonymous product analytics',
      analyticsToggleSubtitle: 'Speech text and reminder names are not sent.',
      trustTitle: 'Privacy and trust',
      trustSubtitle: 'Clear info about analytics, support, and app version.',
      supportTitle: 'Help and support',
      supportSubtitle: 'FAQ, privacy, and support.',
      versionLabel: 'App version',
      internalToolsTitle: 'Internal tools',
      internalToolsSubtitle: 'Low-priority space for events, PostHog, and current device diagnostics.',
      openFounderDashboard: 'Open Founder Dashboard',
      ghostPersonalityTitle: 'Ghost personality',
      ghostPersonalitySubtitle: 'Choose the tone that fits you best',
      helpPrivacyTitle: 'Help and privacy',
      helpPrivacyLink: 'FAQ, privacy, and support',
      adsTitle: 'Ads controls',
      adsSubtitle: 'Internal config. Control ad behavior here before wiring any ad SDK.',
      adsEnabled: 'Enable ads',
      adsEnabledSubtitle: 'Turn ads on or off from here instead of hardcoding them.',
      adsProvider: 'Ads provider',
      homeBanner: 'Home banner',
      homeBannerSubtitle: 'Prepared only. It stays invisible until a real SDK is connected.',
      interstitialEvery: 'Interstitial every X actions',
      noInterstitial: 'None',
      hideForSubscribers: 'Hide ads for future subscribers',
      hideForSubscribersSubtitle: 'Ready for a future subscription path with no extra restructuring.',
      connectGoogle: 'Connect Google Calendar',
      disconnectGoogle: 'Disconnect Google Calendar',
      connecting: 'Connecting...',
      disconnecting: 'Disconnecting...',
      notificationActionBlocked: 'Open device settings',
      notificationActionAsk: 'Enable notifications',
    },
    help: {
      title: 'Help and privacy',
      privacyTitle: 'Privacy summary',
      privacySubtitle: 'A quick user-facing summary of how the current app behaves.',
      permissionsTitle: 'Notifications and permissions',
      deviceDataTitle: 'Data on your device',
      resetAllData: 'Clear all local data',
      resetTitle: 'Clear local data',
      resetBody: 'This will delete all reminders and settings stored on this device only.',
      cancel: 'Cancel',
      reset: 'Clear',
    },
    speechFailed: {
      title: 'Recording did not finish the right way',
      transcriptLabel: 'Captured text',
    },
  },
} as const;

export function getAppCopy(language: UiLanguage) {
  return appCopy[language];
}

export function isEnglishLanguage(language: UiLanguage) {
  return language === 'en';
}
